name: Terraform EC2 

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deployement
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Artifact
        run: ls -ltra

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Prep Terraform Binaries
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="ami_id=${{ secrets.AMI_ID }}" -var="key_name=${{ secrets.KEY_NAME }}"
        working-directory: terraform
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_ami_id: ${{ secrets.AMI_ID }}
            TF_VAR_key_name: ${{ secrets.KEY_NAME }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_ami_id: ${{ secrets.AMI_ID }}
            TF_VAR_key_name: ${{ secrets.KEY_NAME }}
      - name: Capture Terraform Outputs
        id: tf
        run: |
          echo "JAVA_IP=$(terraform output -raw java_node_ip)" >> $GITHUB_ENV
          echo "NGINX_IP=$(terraform output -raw nginx_node_ip)" >> $GITHUB_ENV
          echo "ANSIBLE_IP=$(terraform output -raw ansible_node_ip)" >> $GITHUB_ENV
        working-directory: terraform

      - name: Show Outputs
        run: |
            echo "Java Node IP: ${{ env.JAVA_IP }}"
            echo "Nginx Node IP: ${{ env.NGINX_IP }}"
            echo "Ansible Node IP: ${{ env.ANSIBLE_IP }}"   

      - name: Terraform Destroy 
        if: github.event_name == 'workflow_dispatch'
        working-directory: terraform
        run: terraform destroy -auto-approve



    
      